### ISSUE TITLE
Did you get awesome-switcher to work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [TorchedSammy/dotfiles#1]
Hi,
I've copied your config line
`local switcher = require 'modules.awesome-switcher'`
to my rc.lua and 
created modules folder which has the awesome-switcher and there were tons of errors.

Is there some not so obvious ways to get it work?

**Comment by TorchedSammy** [comment]
can u follow the instructions at the actual github repo: https://github.com/troglobit/awesome-switcher
thats the obvious way to get it to work
i dont recommend just copying and moving from my config
